# Generated by Django 4.2.7 on 2024-01-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency_rate", models.FloatField()),
                ("pub_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
